/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Doc Explorations
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type ErrorResponseErrors = { [key: string]: unknown };

export interface ErrorResponse {
  errors?: ErrorResponseErrors;
}

export type UserRequestUser = {
  email: string;
  name: string;
};

export interface UserRequest {
  user: UserRequestUser;
}

export interface UserResponse {
  email: string;
  id: number;
  name: string;
}

/**
 * @summary Create a new user
 */
export const apiDocExplorationsWebUserControllerCreate = <TData = AxiosResponse<UserResponse>>(
    userRequest?: UserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:4000/api/users`,
      userRequest,options
    );
  }

/**
 * @summary Get a user by ID
 */
export const apiDocExplorationsWebUserControllerShow = <TData = AxiosResponse<UserResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:4000/api/users/${id}`,options
    );
  }

export type ApiDocExplorationsWebUserControllerCreateResult = AxiosResponse<UserResponse>
export type ApiDocExplorationsWebUserControllerShowResult = AxiosResponse<UserResponse>
